# Pega does not actively update this Elasticsearch dependency. To use the SRS to provide an Elasticsearch service to your deployment you must:
# * Update the elasticsearch 'version' value parameter below. This version value must match the 'elasticsearch.imageTag' in the backingservices values.yaml).
# * For kubernetes version >=1.25 or Elasticsearch image version 7.17.9 use Elasticsearch helm chart version 7.17.3, or
# * Disable deploying Elasticsearch in SRS by setting 'srs.srsStorage.provisionInternalESCluster' in backingservices values.yaml to false.
dependencies:
- name: elasticsearch
  version: "7.10.2"
  repository: https://helm.elastic.co/
  condition: srs.srsStorage.provisionInternalESCluster
